# 250708 (화) - 2주차
## 모듈과 패키지, 예외처리

목차
- [List Comprehension](#list-comprehension)
- [Map](#map)
- [filter](#filter)
- [Enumerate & Zip](#filter)
- [Reduce](#reduce)
- [Generator](#generator)
<br/>

~~문자열 출려과 관련해서 정규식에 관해서도 공부하였지만, 익숙지 않아서 추후 정리하도록 한다.~~ 

### 모듈
재사용성을 위해 파이썬 소스 파일을 모듈로 사용한다. py 확장자인 소스 파일로만 가능하다.

```py
import 모듈
import 모듈1, 모듈2 # 모듈을 여러개 가져올 때는 ','로 가져온다.

모듈.변수
모듈.함수()
모듈.클래스()
```

모듈을 사용하려고 가져올 때는 ``from 주소 import 모듈``로 작성한다. 그럼 이 때 ``from time import time``은 어떻게 가능한 것일까? 
-> time은 **표준 라이브러리**라서 미리 정해진 경로로 모듈을 자동으로 찾아준다. 

### 패키지
- 여러 개의 모듈을 하나의 폴더에서 관리를 하는 것. 폴더를 패키지로 인식하지 않을 때는 ``__init__.py``가 있으면 패키지로 인식한다.

```py
# 폴더 크기 측정 함수 만들기

from pathlib import Path
from step_2_1 import WORK_DIR # 이전에 작성한 모듈을 불러온다.

def get_total_filesize(base_dir: Path, pattern: str = "*") -> int:
    total_bytes = 0
    for fullpath in base_dir.glob(pattern): # 글로브 패턴과 일치하는 파일명을 리스트로 반환. *는 모든 파일을 뜻한다.
        if fullpath.is_file():
            total_bytes += fullpath.stat().st_size
    return total_bytes

if __name__ == "__main__": # 소스 코드 최초 실행시 실행. 다른 말로는 import 해서 사용할 때는 실행이 되지 않는다.
    base_dir = WORK_DIR
    filesize = get_total_filesize(base_dir, pattern="*")
    print(f"{base_dir.as_posix()=}, {filesize=} bytes")

```
위 코드는 '혼공파' ch1에서 구현한 step_2_2 모듈이다. 아래 쪽에 ``if __name__ == "__main__"`` 을 통해서 모듈로 실행하는 것인지, 자신이 직접 사용하는 것인지 구분할 수 있다.
``__main__`` 일 때는 자신, 모듈명일 때는 모듈로 실행한 것이다.

#### 패키지 설치하기
다른 사람이 만든 패키지를 설치하는 방법도 있다. 터미널에서 다음과 같이 코드를 작성하면 된다.
``!pip install 패키지이름``

<br/>

### 예외처리

일반적으로 코드가 실행될 때 에러가 생기면 비정상종료가 된다. 그렇게 되면 사용자가 큰 불편을 겪게 되며 데이터 손실 등이 일어날 수 있다.
따라서 비정상종료를 막기 위해 에러가 발생된 이후의 코드들은 정상 작동할 수 있도록 하는 것이 '예외처리' 이다.

```py
try : # 오류가 날 수 있는 코드이다. 잘 살펴보자.
    ~
except : # 오류가 났는가? 그렇다면 아래와 같이 실행하여라
    ~
else : # 오류가 나지 않고 잘 작동했다면, 아래와 같이 실행하여라
    ~
finally : # 오류에 상관없이 아래는 꼭 실행하여라
    ~
```

예외에는 다양한 것들이 있다. EOFError, IndexError, NameError 등 쉽게 찾아볼 수 있다. 만약 특정 error에 맞게 예외 처리를 하려면 다음과 같이 한다.
```py
try :
    ~
except (NameError, IndexError) as e :
    ~
    print(e)
```

예시인 NameError와 IndexError는 except를 추가로 작성해서 분리해서 작성할 수 있다. 또한 as e 를 통해 에러 메세지를 ``print(e)``를 통해서 볼 수 있다.
만약 정확한 에러를 알지 못해 예외처리가 힘들다면 다음과 같이 한다.
```py
try:
    ~
except Exception as e:
    ~
    print(e)
```
``Exception``을 통해서 예외인 부분을 알아낼 수 있다.

#### 사용자 전용 에러 예외 처리하기
```py
class NegativeDivisionError(Exception): # Exception을 상속받아서 class 생성.
    def __init__(self, value):
        self.value = value

def PositiveDivide(a, b):
    if (b<0):
        raise NegativeDivisionError(f'{b}로는 나눌 수 없습니다.') 
        # raise를 이용해서 생성한 Error Exception을 실행시킨다.
        # 사용자가 임의로 에러를 만들어서 에러의 클래스까지 따로 만들어서 처리
    return a / b

try:
    ex = PositiveDivide(3,-14)
except ZeroDivisionError as e: # 미리 정해진 오류 예외처리
        print( e, 'ZeroDivisionError' )
except NegativeDivisionError as e: # NegativeDivisionError: -11, 
        # PositiveDivide()에서 정의된 예외 처리가 있어서 실행된다.
        print( e, 'NegativeDivisionError' )
except Exception as e:
    print( e, 'Exception' )
```